version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hris_postgres_local
    restart: always
    environment:
      POSTGRES_USER: hrisuser
      POSTGRES_PASSWORD: hrispassword
      POSTGRES_DB: hris_saas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
